Repository AnnTarou/HelloQuery, pull requests merged in 2024-06, with the labels that each got.

#66 Feature/a0003 #60
  HelloQuery/Views/Lessons/AnswerPage.cshtml
  HelloQuery/Views/Lessons/Index.cshtml
  HelloQuery/Views/Lessons/_LessonsPartial.cshtml
  HelloQuery/Views/UserLessons/Index.cshtml
Labels: 実装

#67 develop/A0003 →　feature/A0003_#62 pull request
  HelloQuery/Views/Lessons/AnswerPage.cshtml
  HelloQuery/Views/Lessons/Index.cshtml
  HelloQuery/Views/Lessons/_LessonsPartial.cshtml
  HelloQuery/Views/UserLessons/Index.cshtml
Labels: developからプルリク

#68 develop/A0003 →　test/A0003_#65
  HelloQuery/Views/Lessons/AnswerPage.cshtml
  HelloQuery/Views/Lessons/Index.cshtml
  HelloQuery/Views/Lessons/_LessonsPartial.cshtml
  HelloQuery/Views/UserLessons/Index.cshtml
Labels: developからプルリク

#69 Feature/a0003 #62
  HelloQuery/Data/SeedData.cs
Labels: 修正

#70 develop/A0003 →　test/A0003_#65 pull request
  HelloQuery/Data/SeedData.cs
Labels: developからプルリク

#72 エラーページと処理追加
  HelloQuery/Controllers/AccountController.cs
  HelloQuery/Controllers/ErrorController.cs
  HelloQuery/Controllers/HomeController.cs
  HelloQuery/Controllers/UserLessonsController.cs
  HelloQuery/Controllers/UsersController.cs
  HelloQuery/Views/Error/error.cshtml
  HelloQuery/Views/UserLessons/Details.cshtml
  HelloQuery/Views/Users/Delete.cshtml
Labels: 実装

#73 develop/A0003 →　test/A0003_#65 pull request
  HelloQuery/Controllers/AccountController.cs
  HelloQuery/Controllers/ErrorController.cs
  HelloQuery/Controllers/HomeController.cs
  HelloQuery/Controllers/UserLessonsController.cs
  HelloQuery/Controllers/UsersController.cs
  HelloQuery/Views/Error/error.cshtml
  HelloQuery/Views/UserLessons/Details.cshtml
  HelloQuery/Views/Users/Delete.cshtml
Labels: developからプルリク

#74 develop/A0003 →　feature/A0003_#54 pull request
  HelloQuery/Controllers/AccountController.cs
  HelloQuery/Controllers/ErrorController.cs
  HelloQuery/Controllers/HomeController.cs
  HelloQuery/Controllers/UserLessonsController.cs
  HelloQuery/Controllers/UsersController.cs
  HelloQuery/Views/Error/error.cshtml
  HelloQuery/Views/UserLessons/Details.cshtml
  HelloQuery/Views/Users/Delete.cshtml
Labels: developからプルリク

#78 develop/A0003 →　feature/A0003_#54 pull request
  HelloQuery/Controllers/UsersController.cs
Labels: developからプルリク

#81 Feature/a0003 #54
  HelloQuery/Controllers/LessonsController.cs
  HelloQuery/Models/LessonViewModel.cs
  HelloQuery/Views/Lessons/_AnswerPartial.cshtml
  HelloQuery/Views/Lessons/_LessonsPartial.cshtml
Labels: 実装

#82 エラー処理追加その他処理追加
  HelloQuery/Controllers/LessonsController.cs
  HelloQuery/Controllers/UsersController.cs
  HelloQuery/Views/Account/Login.cshtml
  HelloQuery/Views/Lessons/AnswerPage.cshtml
  HelloQuery/Views/Lessons/Index.cshtml
  HelloQuery/Views/Lessons/_AnswerPartial.cshtml
Labels: 修正

#85 修正
  HelloQuery/Views/Account/Login.cshtml
  HelloQuery/Views/Lessons/AnswerPage.cshtml
  HelloQuery/Views/Lessons/Index.cshtml
  HelloQuery/Views/Lessons/_AnswerPartial.cshtml
  HelloQuery/Views/Lessons/_LessonsPartial.cshtml
  HelloQuery/Views/UserLessons/Index.cshtml
  HelloQuery/Views/Users/Create.cshtml
Labels: 修正

#88 文字位置修正
  HelloQuery/Views/Account/ForgotPassword.cshtml
Labels: 修正

#90 Feature/a0003 #86
  HelloQuery/Controllers/LessonsController.cs
  HelloQuery/Data/SeedData.cs
  HelloQuery/Views/Lessons/_AnswerPartial.cshtml
Labels: 修正

#92 エラー処理修正最終チェック
  HelloQuery/Controllers/LessonsController.cs
  HelloQuery/Controllers/UsersController.cs
  HelloQuery/Views/Account/ForgotPassword.cshtml
  HelloQuery/Views/Lessons/_AnswerPartial.cshtml
  HelloQuery/Views/Lessons/_LessonsPartial.cshtml
  HelloQuery/Views/Users/Delete.cshtml
  HelloQuery/Views/Users/Edit.cshtml
Labels: 修正

#95 正誤判定の修正 #94
  HelloQuery/Controllers/LessonsController.cs
Labels: 修正

#97 サイトの説明
  HelloQuery/Views/Home/Index.cshtml
Labels: 実装

#100 DB接続文字列変更他　＃99
  HelloQuery/Data/SeedData.cs
  HelloQuery/Program.cs
  HelloQuery/Views/Lessons/AnswerPage.cshtml
  HelloQuery/Views/Lessons/Index.cshtml
  HelloQuery/appsettings.json
Labels: 修正
